### ISSUE TITLE
Super cool

### ISSUE THREAD

**Issue by onemanstartup** [planningcenter/react-patterns#13]
Just want ask some questions.
1. Do you use flux? If so, do you found some patterns already?
2. If you don't use cjsx how do you feel about things like
https://github.com/adelevie/react-tags
https://github.com/kalasjocke/react-coffee-elements
or just plain $ = React.DOM
3. Do you have an opinion on how to structure folder structures? For example like
- components
 - pure_components
 - containers
 - pages

Coming from rails and ruby, i feel lack of established conventions yet, but hope we all get to the promise land.

**Comment by chantastic** [comment]
Hi @onemanstartup. Sorry for the delay. I totally missed this:

1. We do use Flux. @seven1m has some great thoughts from his experience detailed here: https://github.com/planningcenter/flux-patterns
2. We never really felt the need to use react-tags or react-coffee-elements. Or goal in removing CJSX was to limit the number of dependencies we needed in place to write React components. In practice, we'll destructure the elements out of `React.DOM`, as you mentioned. To be quite honest, we've started writing less CoffeeScript and using JSX/JS. We do all new components in JS/JSX.
3. We put everything in `components.` Personally, I don't like the idea of separating/naming classes by pattern. But that argument definitely has to sides :)

**Comment by onemanstartup** [comment]
Don't worry about delay :)
Everything in components will soon become unmanageable. 
Anyway thanks for reply.

**Comment by chantastic** [comment]
Yah. It does seem like `containers` seems like a totally logical dividing line.
