### ISSUE TITLE
Computed Props pattern doesn't work

### ISSUE THREAD

**Issue by jscheel** [planningcenter/react-patterns#30]
The "this" context appears to be different when defining a getter. See http://stackoverflow.com/questions/27440581/why-getters-dont-have-access-to-state-in-react-components.

I haven't been able to get this to work and have resorted to simple functions instead. Am I doing something wrong?

**Comment by chantastic** [comment]
Sounds like you're using `createClass` instead of the ES6 `Component` class. Is that correct? If so, getters will not work.

**Comment by jscheel** [comment]
I'm using ES6, here's a gist: https://gist.github.com/jscheel/60c97d0b1fd43df48de1

**Comment by chantastic** [comment]
In the case of `createClass` I recommend what your doing, just adding a function to the spec object. I like to prefix these types of functions with `get`

**Comment by danott** [comment]
@jscheel I'm curious what version of React  you using?

I was able to successfully demonstrate getters working on 0.13.0 [in this CodePen](http://codepen.io/anon/pen/NGLzNO)

**Comment by jscheel** [comment]
I'm on 0.14.0.

**Comment by chantastic** [comment]
Curious. TBH, I have yet to update any components that do this to 0.14.

**Comment by chantastic** [comment]
Away from the keyboard, at the moment. I won't be much help tile later.

**Comment by danott** [comment]
@jscheel I have updated the codepen to use `0.14.0`, and it is still working as expected. I wonder if there are any other outside factors we can consider?

**Comment by jscheel** [comment]
@danott Hmm, it's definitely possible. Let me investigate a bit.
@chantastic No worries!

**Comment by jscheel** [comment]
Ok, I tracked it down. The yeoman generator Webpack is using react-hot-loader which doesn't like this for some reason.

**Comment by chantastic** [comment]
@jscheel that's super weird. i wouldn't have guessed that it would cause issues at that level. sorry you're having issues with it.

**Comment by jscheel** [comment]
No worries! Apparently react-hot-loader is deprecated anyways.
