### ISSUE TITLE
The whys?

### ISSUE THREAD

**Issue by rulatir** [planningcenter/react-patterns#33]
Each pattern section should have a "why" subsection section that argues its point. You don't just state "this is a good pattern, follow it blindly". This is particularly important in those instances where the "good" version has obvious drawbacks, like having 3× as much code.

**Comment by chantastic** [comment]
@rulatir just wanted to let you know that i started work on a new page for patterns that talks about some of these more holistically. i'll be adding to it over the next couple weeks. i hope that this helps answer more of "the whys". http://reactpatterns.com/

I'm going to close the issue now that the new site is up.
