### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by thaithco** [planningcenter/react-patterns#36]
Under _Prefer Ternary to Sub-render_, it says:

> Keep login inside the render.

What is login?

From the examples, it seems that the overall goal is to keep render code within the render function. Should it say something like _Keep render code inside the render (function)_ ?

**Comment by geolessel** [comment]
Yes, it looks like that should be

> Keep logic inside the render.

I'll fix that up. Thanks!

**Comment by geolessel** [comment]
PR #38
