### ISSUE TITLE
JSX escapes HTML entities and special characters

### ISSUE THREAD

**Issue by falldowngoboone** [planningcenter/react-patterns#42]
I'm proposing updating the Using Entities section. The [Babel JSX parser](https://github.com/babel/babel/blob/eac4c5bc17133c2857f2c94c1a6a8643e3b547a7/packages/babel-parser/src/plugins/jsx/index.js) automatically escapes HTML entities now. Granted, this is not part of the official [JSX spec](https://facebook.github.io/jsx/), but I would think most people using JSX with React are transpiring with Babel now.

I've submitted #41 to address this. Open to any suggestions (this is my first official PR to someone else's open source project).

**Comment by falldowngoboone** [comment]
Looking though, I realized this was meant for React on Rails. Closing issue.

**Comment by chantastic** [comment]
Hi @falldowngoboone!

Thanks so much for your support.
Yeah, I've kept this around for historical (sentimental) reasons but I've evolved it into [reactpatterns.com](https://reactpatterns.com), where I'll be adding more articles.

Thanks for the support.

Michael
